# Configuração basica de CI/CD
name: CI-CD

# Controle de quando irá executar 
on:
  # restrições dos gatilhos de execução
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Permite execução manual
  workflow_dispatch:

# Tarefas 
jobs:
  CI:
    # Tipo do executor
    runs-on: ubuntu-latest

    # Sequencia de atividades do processo de build
    steps:
      # Checks-out do projeto
      - uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKERHUB_USR }}
          password: ${{ secrets.DOCKERHUB_PWD }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2.6.1
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: |
            schleuss/rotten-potatoes:latest
            schleuss/rotten-potatoes:b${{ github.run_number }}

  CD:
    runs-on: ubuntu-latest
    needs: [ CI ]
    steps:
      - uses: actions/checkout@v2
      
      - name: Kubernetes set context
        uses: Azure/k8s-set-context@v1.1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.K8S_CONFIG }}
          
      - name: Deploy MongoDB
        uses: Azure/k8s-deploy@v1
        with:
          manifests: |
            k8s/mongodb/deployment.yml
            k8s/mongodb/service.yml
          
      - name: Deploy App
        uses: Azure/k8s-deploy@v1
        with:
          manifests: |
            k8s/app/deployment.yml
            k8s/app/service-cloud.yml
          images: schleuss/rotten-potatoes:b${{ github.run_number }}
