# Configuração basica de CI/CD
name: CI-CD

# Controle de quando irá executar 
on:
  # restrições dos gatilhos de execução
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Permite execução manual
  workflow_dispatch:

# Tarefas 
jobs:
  build:
    # Tipo do executor
    runs-on: ubuntu-latest

    # Sequencia de atividades do processo de build
    steps:
      # Checks-out do projeto
      - uses: actions/checkout@v2

      # Executar comando - única linha
      - name: Run a one-line script
        run: echo Hello, world!

      # Executar comando - múltplas linhas
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
