# Configuração basica de CI/CD
name: CI-CD

# Controle de quando irá executar 
on:
  # restrições dos gatilhos de execução
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Permite execução manual
  workflow_dispatch:

# Tarefas 
jobs:
  build:
    # Tipo do executor
    runs-on: ubuntu-latest

    # Sequencia de atividades do processo de build
    steps:
      # Checks-out do projeto
      - uses: actions/checkout@v2
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.6.1
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: |
            schleuss/rotten-potatoes:latest
            schleuss/rotten-potatoes:b${{ github.run_number }}

            
